version: '3'
services:
    redalert:
        restart: unless-stopped
        image: kfir/redalert
        environment: 
            MQTT_HOST: ${MQTT_HOST}
            MQTT_PORT: ${MQTT_PORT}
            MQTT_USER: ${MQTT_USER}
            MQTT_PASS: ${MQTT_PASS}

             